import inflection

str = """Code
Year
Type
Description
ProductSetCode
PackageCode
BeverageCategoryCode
UnitsPerCases
QtyPerEach
EqCasesPerPackage
IsForecast
PlanningSuperCategoryCode
PlanningSuperCategory
PlanningCategoryCode
PlanningCategory
PlanningPackageGroupCode
PlanningPackageGroup
PlanningConsumptionCategoryCode
PlanningConsumptionCategory"""

print(inflection.underscore(str))